site_name: Hyperqueue

site_url: https://spirali.github.io/hyperqueue/
repo_url: https://github.com/spirali/hyperqueue
edit_uri: blob/main/docs/

site_description: Documentation of HyperQueue.
site_author: Stanislav Böhm

nav:
  - Overview: README.md
  - Installation: install.md
  - Cheatsheet: cheatsheet.md
  - Deployment: deployment.md
  - Jobs (Basics): jobs.md
  - Task Arrays: arrays.md
  - CPU management: cpus.md
  - Cookbook:
    - Handling many output files: cookbook/handling_many_files.md


theme:
  name: readthedocs
  custom_dir: docs/theme
  highlightjs: true
  hljs_languages:
    - bash

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition

plugins:
  - search
