on:
  pull_request_target:

name: Check binary size

jobs:
  bloat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Run cargo bloat
        uses: kobzol/cargo-bloat-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
